name: Generate Snake Animation

on:
  # 安排任务：每 2 小时自动运行一次
  schedule:
    - cron: "0 */2 * * *" 
  # 允许手动运行
  workflow_dispatch:
  # 每次推送到 master (或 main) 分支时运行
  push:
    branches:
      - master # 如果你的主分支叫 main，请改成 main

jobs:
  generate:
    permissions: 
      contents: write # 给予 workflow 写入仓库内容的权限
    runs-on: ubuntu-latest # 在最新的 Ubuntu 系统上运行
    timeout-minutes: 5 # 设置超时时间为 5 分钟

    steps:
      # 第一步：生成贪吃蛇 SVG 动画
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3 # 使用 Platane/snk 这个现成的 Action
        with:
          github_user_name: ${{ github.repository_owner }} # 自动获取你的 GitHub 用户名
          outputs: | # 指定输出的文件路径和样式
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 第二步：将生成的 SVG 文件推送到 output 分支
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0 # 使用 crazy-max/ghaction-github-pages 这个 Action
        with:
          target_branch: output # 目标分支叫 output（如果不存在会自动创建）
          build_dir: dist # 要推送的文件夹是 dist（上一步生成的文件就在这里）
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub 提供的 Token 进行认证
